# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-01 04:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wiki', '0004_auto_20171001_0605'),
    ]

    operations = [
        migrations.CreateModel(
            name='Input',
            fields=[
                ('articleplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wiki.ArticlePlugin')),
                ('key', models.CharField(max_length=28)),
                ('val', models.TextField()),
                ('owner', models.ForeignKey(help_text='The author of the input. The owner always has both read access.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_inputs', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
            ],
            options={
                'verbose_name': 'Input',
                'verbose_name_plural': 'Inputs',
                'get_latest_by': 'created',
            },
            bases=('wiki.articleplugin',),
        ),
        migrations.CreateModel(
            name='InputDefinition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=28)),
                ('expr', models.TextField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wiki.Article')),
            ],
        ),
        migrations.CreateModel(
            name='InputDependency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=28)),
                ('per_owner', models.BooleanField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wiki.Article')),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_wiki_forms.InputDefinition')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='inputdefinition',
            unique_together=set([('article', 'key')]),
        ),
    ]
