# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 22:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('django_wiki_forms', '0002_input_newer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inputdependency',
            old_name='definition',
            new_name='idef',
        ),
        migrations.RenameField(
            model_name='inputdependency',
            old_name='per_owner',
            new_name='per_user',
        ),
        migrations.AddField(
            model_name='input',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_inputs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inputdefinition',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inputdefinition',
            name='per_user',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='input',
            name='val',
            field=models.TextField(blank=True, null=True),
        ),
    ]
