# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-07 00:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('django_wiki_forms', '0003_update_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='InputDefValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('val', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Calculated Input',
                'verbose_name_plural': 'Calculated Inputs',
                'get_latest_by': 'created',
            },
        ),
        migrations.RemoveField(
            model_name='inputdefinition',
            name='created',
        ),
        migrations.AddField(
            model_name='inputdependency',
            name='depend_idef',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='depend_on', to='django_wiki_forms.InputDefinition'),
        ),
        migrations.AlterField(
            model_name='inputdependency',
            name='idef',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencies', to='django_wiki_forms.InputDefinition'),
        ),
        migrations.AddField(
            model_name='inputdefvalue',
            name='idef',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='django_wiki_forms.InputDefinition'),
        ),
        migrations.AddField(
            model_name='inputdefvalue',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='The author of the input. The owner always has both read access.', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='owner'),
        ),
        migrations.AlterUniqueTogether(
            name='inputdefvalue',
            unique_together=set([('idef', 'owner')]),
        ),
    ]
