# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-09 03:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('django_wiki_forms', '0004_add_values'),
    ]

    operations = [
        migrations.CreateModel(
            name='InputDocker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=255)),
                ('scenario', models.CharField(max_length=255)),
                ('args', models.TextField(blank=True, null=True)),
                ('container_id', models.CharField(blank=True, max_length=64, null=True)),
                ('val', models.TextField(blank=True, null=True)),
                ('idef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_wiki_forms.InputDefinition')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='owner')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='inputdocker',
            unique_together=set([('idef', 'owner', 'image', 'scenario', 'args')]),
        ),
    ]
