# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-15 06:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_wiki_forms', '0008_update_input_part1'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InputNew',
            new_name='Input',
        ),
        migrations.RemoveField(
            model_name='inputold',
            name='articleplugin_ptr',
        ),
        migrations.RemoveField(
            model_name='inputold',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='inputold',
            name='newer',
        ),
        migrations.RemoveField(
            model_name='inputold',
            name='owner',
        ),
        migrations.DeleteModel(
            name='InputOld',
        ),
        migrations.AlterUniqueTogether(
            name='input',
            unique_together=set([('article', 'owner', 'name', 'newer')]),
        ),
        migrations.RunSQL("CREATE UNIQUE INDEX django_wiki_forms_input_unique1 ON django_wiki_forms_input (article_id, name) WHERE owner_id IS NULL AND newer_id IS NULL;"),
        migrations.RunSQL("CREATE UNIQUE INDEX django_wiki_forms_input_unique2 ON django_wiki_forms_input (article_id, name, owner_id) WHERE newer_id IS NULL;"),
        migrations.RunSQL("CREATE UNIQUE INDEX django_wiki_forms_inputdef_unique ON django_wiki_forms_inputdefvalue (idef_id) WHERE owner_id IS NULL;"),
        migrations.RunSQL("INSERT INTO django_wiki_forms_input(id, created, name, article_id, owner_id) VALUES (0, to_timestamp(0), '', 1, 1);")
    ]
