# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-15 23:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_wiki_forms', '0009_auto_20171115_0846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputdocker',
            name='scenario',
            field=models.TextField(),
        ),
    ]
