# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-22 08:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_wiki_forms', '0010_auto_20171116_0035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inputdocker',
            name='scenario',
        ),
    ]
